### ISSUE TITLE
Download link for VLCI model not working

### ISSUE THREAD

**Issue by MIAWU-jojo** [WissingChen/VLCI#1]
Hi there, I'm trying to download the well-trained models of VLCI for inference from the link provided in the README, but the link appears to be broken. When I click on it, I receive an error message saying the page cannot be found. Could you please update the download link or provide an alternate method for accessing the models? Thanks!

**Comment by WissingChen** [comment]
maybe you can try this link: https://mega.nz/folder/C1IynThZ#M_Ge80DUVkT1HdvIhL1k2g

**Comment by Junyiliu0** [comment]
> maybe you can try this link: https://mega.nz/folder/C1IynThZ#M_Ge80DUVkT1HdvIhL1k2g

Hello, this link is also broken~

**Comment by WissingChen** [comment]
got it, maybe the link has a limited term, so I change it to the Baidu Netdisk.

**Comment by WissingChen** [comment]
👌 got it, maybe the link has a limited term, so I change it to the Baidu Netdisk.  Please refer to the readme in the current version.

**Comment by WissingChen** [comment]
sorry, I have updated the code, thank you for your response.

Regard,
wissing

Junyiliu0 ***@***.***> 于2023年8月16日周三 15:50写道：

**Comment by RongxingLin** [comment]
你好，我这边想下载你提供的训练好的模型，点击你在README中提供的百度网盘链接，显示是文件已过期，可以更新一下链接吗？或者可以提供一个下载的渠道吗？谢谢！

**Comment by WissingChen** [comment]
我更新readme中的下载链接了

**Comment by RongxingLin** [comment]
> 我更新readme中的下载链接了
非常感谢！
