### ISSUE TITLE
CE metrics

### ISSUE THREAD

**Issue by weichen5926** [WissingChen/VLCI#2]
This is a good job that has inspired me greatly. However, I'm not clear on how the CE metrics (Precision, Recall, F1-Score) in the paper are calculated, and I haven't been able to find it in the source code either. I would like to ask how missing values are handled after CheXpert extracts labels. From what I've searched, there are two methods: one is to treat missing values as 0 and treat the remaining values (1,-1,0) as 1 (as shown in https://github.com/MIT-LCP/mimic-cxr/blob/master/txt/validation/compare_negbio_and_chexpert.ipynb), while the other is to treat missing values as 0 and keep the remaining labels unchanged for calculation. Alternatively, there may be other ways of handling. Could you please let me know which method was used or provide the relevant code for this?

**Comment by WissingChen** [comment]
The method which treats missing values as 0 and treats the remaining values (1,-1,0) as 1, is the “mention” mode in CheXpert. We adopt the latter approach to calculate the CE metrics.

**Comment by weichen5926** [comment]
Thank you for your answer.
