### ISSUE TITLE
MIMIC-CXR Annotation JSon

### ISSUE THREAD

**Issue by mkara44** [WissingChen/VLCI#4]
Hi!

Thanks for the paper and implemantation. Both are perfect! I am trying to run inference on my X-Ray dataset, however tokenizer module needs annotation.json files for both MIMIC-CXR and IU X-Ray datasets. I found the IU X-Ray's, but could not find the MIMIC-CXR. I requested, but it would be wonderful if you provide ONLY annotation json file. 

Thanks

**Comment by WissingChen** [comment]
I am sorry about the late reply, here is the annotation.json of MIMIC-CXR.[https://drive.google.com/file/d/14jAJy0ajRwFvdTXsH54921tLcuvzfEd3/view?usp=share_link](url)

**Comment by Mai-CS** [comment]
File is removed.

**Comment by WissingChen** [comment]
Sorry for not replying to you sooner, but I've been busy lately. You can
download the MIMIC-CXR dataset from this link:
https://pan.baidu.com/s/1OxD644KSKZUXfGAQj4VEvA?pwd=049r

Mai A. Shaaban ***@***.***> 于2024年11月10日周日 23:50写道：
