### ISSUE TITLE
MixTokenizer Mimic-CXR Dataset Annotation Path Bug

### ISSUE THREAD

**Issue by mkara44** [WissingChen/VLCI#5]
Hi!

Thanks for the implementation. I am working on your repository and I realized that your MixTokenizer reads only IU Xray annotations. Even Mimic-CXR annotation.json path is defined above code lines, IU Xray's json path is given for Mimic-CXR too. Also your pretrained models were trained with this bug. They are only loaded with this configuration.  You can see the wrong line from the link below.

https://github.com/WissingChen/VLCI/blob/216038fe28e1fb9e3d2fee5b7c76b8dc843c4397/utils/tokenizers.py#LL132C53-L132C53

**Comment by WissingChen** [comment]
I'm sorry, I have fixed the bug, please look at the latest version.
